#!/usr/bin/env python3
"""Render InkyOS hardware-derived files from the shared contract.

``meta/shared/hardware.toml`` is the single source of truth (ADR 0008) for the
panel geometry, GPIO/SPI pin map, and button bindings. buildroot_os must not
hard-code those values; this script renders them into the two committed files
that need them:

    board/inky/config.txt
        Raspberry Pi firmware config: enable SPI, set button GPIO pull-ups.

    board/qemu/overlay/opt/the_question/game/input_hook.rpy
        The in-engine button NAME -> renpy_events map (only the region between
        the GENERATED sentinels is owned by this script; the rest is hand-written).

Usage::

    python3 scripts/gen_hardware.py            # regenerate in place
    python3 scripts/gen_hardware.py --check    # verify; write nothing (exit 1 on drift)
    python3 scripts/gen_hardware.py --contract PATH

The contract is located (in order) via --contract, $EINKY_HARDWARE_TOML,
$EINKY_META_DIR/shared/hardware.toml, then ../meta/shared/hardware.toml relative
to this repo (the sibling-checkout convention). If none exists the script prints
a warning and exits 0 -- parity can only be enforced where the contract is present.
"""

from __future__ import annotations

import argparse
import os
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

INPUT_HOOK = REPO_ROOT / "board/qemu/overlay/opt/the_question/game/input_hook.rpy"
CONFIG_TXT = REPO_ROOT / "board/inky/config.txt"

_MAP_BEGIN = "# >>> GENERATED button-map"
_MAP_END = "# <<< GENERATED button-map"


def find_contract(explicit: Path | None) -> Path | None:
    candidates = []
    if explicit:
        candidates.append(explicit)
    if os.environ.get("EINKY_HARDWARE_TOML"):
        candidates.append(Path(os.environ["EINKY_HARDWARE_TOML"]))
    if os.environ.get("EINKY_META_DIR"):
        candidates.append(Path(os.environ["EINKY_META_DIR"]) / "shared/hardware.toml")
    candidates.append(REPO_ROOT.parent / "meta/shared/hardware.toml")
    for c in candidates:
        if c.exists():
            return c
    return None


def load_contract(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


# ── renderers ─────────────────────────────────────────────────────────────────


def render_config_txt(c: dict) -> str:
    panel = c["panel"]
    spi = c["spi"]
    buttons = c["button"]
    btn_pins = ",".join(str(b["bcm"]) for b in sorted(buttons, key=lambda b: b["bcm"]))
    # active_low / pull / debounce_ms are keys of the [spi] table in the contract.
    pull_kind = spi.get("pull")
    pull = "pu" if pull_kind == "up" else "pd" if pull_kind == "down" else "np"
    pull_word = {"pu": "pull-up", "pd": "pull-down", "np": "no-pull"}[pull]
    btn_lines = "\n".join(f"#   {b['name']:<5} -> BCM {b['bcm']}" for b in buttons)
    return f"""\
# InkyOS Raspberry Pi firmware config.
#
# AUTO-GENERATED by scripts/gen_hardware.py from meta/shared/hardware.toml.
# Do not edit by hand -- change the contract and run `make` (./br.sh runs the
# parity check) or `python3 scripts/gen_hardware.py`. CI fails on drift.
#
# Panel: {panel["model"]} ({panel["width"]}x{panel["height"]}, 1-bit).
# SPI display ([spi], BCM numbering): {spi["dev"]}
#   MOSI=BCM {spi["mosi"]}  SCLK=BCM {spi["sclk"]}  CS=BCM {spi["cs"]}
#   DC=BCM {spi["dc"]}  RST=BCM {spi["rst"]}  BUSY=BCM {spi["busy"]}  (DC/RST/BUSY via libgpiod)
# Buttons (active-low, internal pull-up):
{btn_lines}

# Hardware SPI0 (MOSI/SCLK/CE0 on their fixed ALT0 pins) for the panel.
dtparam=spi=on

# Button GPIOs as inputs with internal {pull_word} at boot (ip,{pull}), matching
# the contract so a press reads its rest level before userspace starts.
gpio={btn_pins}=ip,{pull}
"""


def render_button_map(c: dict) -> str:
    """The GENERATED region of input_hook.rpy (between the sentinels, inclusive)."""
    buttons = c["button"]
    rows = []
    for b in buttons:
        events = ", ".join(f'"{e}"' for e in b["renpy_events"])
        rows.append(f'        "{b["name"]}": [{events}],')
    body = "\n".join(rows)
    return (
        f"    {_MAP_BEGIN} (scripts/gen_hardware.py --check enforces parity) >>>\n"
        "    _INPUT_COMMAND_MAP = {\n"
        f"{body}\n"
        "    }\n"
        f"    {_MAP_END} <<<"
    )


def splice_button_map(existing: str, rendered: str) -> str:
    lines = existing.splitlines()
    begin = next((i for i, ln in enumerate(lines) if _MAP_BEGIN in ln), None)
    end = next((i for i, ln in enumerate(lines) if _MAP_END in ln), None)
    if begin is None or end is None or end < begin:
        raise SystemExit(f"error: GENERATED button-map sentinels not found in {INPUT_HOOK}")
    new_lines = lines[:begin] + rendered.splitlines() + lines[end + 1 :]
    return "\n".join(new_lines) + "\n"


# ── driver ────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    ap.add_argument("--contract", type=Path, default=None)
    args = ap.parse_args(argv)

    contract_path = find_contract(args.contract)
    if contract_path is None:
        print(
            "gen_hardware: hardware.toml not found (set $EINKY_META_DIR or check out "
            "../meta); skipping contract parity.",
            file=sys.stderr,
        )
        return 0

    c = load_contract(contract_path)

    config_body = render_config_txt(c)
    hook_text = INPUT_HOOK.read_text()
    hook_new = splice_button_map(hook_text, render_button_map(c))

    drift = []
    targets = [
        (CONFIG_TXT, config_body, CONFIG_TXT.read_text() if CONFIG_TXT.exists() else None),
        (INPUT_HOOK, hook_new, hook_text),
    ]
    for path, new, current in targets:
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            if current != new:
                drift.append(rel)
                print(f"DRIFT: {rel}", file=sys.stderr)
        elif current != new:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(new)
            print(f"wrote {rel}")
        else:
            print(f"ok    {rel}")

    if args.check and drift:
        print(
            f"\n{len(drift)} file(s) out of sync with {contract_path}. "
            "Run `python3 scripts/gen_hardware.py` and commit.",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print(f"hardware contract parity OK ({contract_path})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
